### ISSUE TITLE
Completed Module 3 Assignments

### ISSUE THREAD

**Issue by stacianordin** [ds4owd-001/md-03-assignments-StaciaNordin#1]
I can’t figure out how to use the ‘print(n = …)’
I tried Posit community & perplexity and still couldn’t figure it out.
Thanks for this course!
@larnsce @mianzg @sskorik01

**Comment by sskorik01** [comment]
Congratulations for making it through, it is a whole process and takes time, but step-by-step it will become clearer. 


The print() function in R has an argument n that controls the number of elements to be printed when displaying an object. It's particularly useful when dealing with large datasets or vectors, allowing you to limit the number of elements displayed to avoid overwhelming the output.

Here's an example demonstrating how to use print() with the n argument:

```{r}
# Create a vector with 10 elements
my_vector <- 1:10

# Printing the vector with default settings
print(my_vector)
# Output will display all 10 elements of the vector

# Printing the vector with a limited number of elements (e.g., 5)
print(my_vector, n = 5)
# Output will display the first 5 elements of the vector

# You can also use it with other objects like data frames
my_data_frame <- data.frame(A = 1:5, B = letters[1:5], C = 6:10)

# Printing the data frame with default settings
print(my_data_frame)
# Output will display the entire data frame

# Printing the data frame with a limited number of rows (e.g., 3)
print(my_data_frame, n = 3)
# Output will display the first 3 rows of the data frame
```

**Comment by stacianordin** [comment]
I'll go back and try it, thanks.
